#' plot_eda()
#'
#' Visualize EDA data for one subject.
#' 
#' @param data; a dataframe generated by summary_eda()
#' @param summary; a dataframe generated by compress_eda()
#' @return dataframe
#' @export

plot_eda <- function(data, summary){
  summary <- data.frame(summary, Time2 = c(summary$Time[-1], tail(summary$Time, n = 1) + 1))
  ggplot() + 
    geom_line(data = data, mapping = aes(x = Time, y = AverageEda), size = 0.75) +
    geom_rect(data = summary, mapping = aes(xmin = Time, ymin = min(data$AverageEda), xmax = Time2, ymax = max(data$AverageEda), fill = Event), alpha = 0.15) +
    geom_point(data = summary, mapping = aes(x = Time, color = Event, y = AverageEda), size = 4 ) +
    geom_rect(data = summary, mapping=aes(xmin = Time, ymin = AverageEda - 0.5, xmax = Time2, ymax = AverageEda +0.5, fill = Event), alpha = 0.4) +
    geom_text(data = summary, mapping=aes(x = Time, y = AverageEda, label = AverageEda), angle=-20, hjust=1.2, vjust = 0.2, size=4.5)
}